export const ActionTypes = {
    // layout actions
    SET_LOADER: "SET_LOADER",
    CHANGE_LANGUAGE:"CHANGE_LANGUAGE",

    // mapView actions 
    SET_VIEW: "SET_VIEW",
    SET_WEBMAP:"SET_WEBMAP",

    // bookMark actions
    FILL_BOOKMARKS:"FILL_BOOKMARKS",
    BOOKMARK_FILTER_TEXT: "BOOKMARK_FILTER_TEXT",

    // mapContainer actions

    // ui actions
    SET_BOOKMARK_VISIBLITY:"SET_BOOKMARK_VISIBLITY",

    // layerList actions

    // trace actions
    SET_UTILITYNETWORK_SPATIALREFERENCE:"SET_UTILITYNETWORK_SPATIALREFERENCE",
    SET_UTILITYNETWORK_SERVICE_URL:"SET_UTILITYNETWORK_SERVICE_URL",
    SET_TRACE_CONFIGURATIONS:"SET_TRACE_CONFIGURATIONS",
    ADD_TRACE_SELECTED_POINT: "ADD_TRACE_SELECTED_POINT",
    ADD_TRACE_LOCATION: "ADD_TRACE_LOCATION",
    REMOVE_TRACE_POINT: "REMOVE_TRACE_POINT",
    SET_CATEGORIZED_ELEMENTS: "SET_CATEGORIZED_ELEMENTS",
    SET_TRACE_CONFIG_HIGHLIGHTS: "SET_TRACE_CONFIG_HIGHLIGHTS",
    SET_UTILITYNETWORK:"SET_UTILITYNETWORK",
    SET_ASSETS_DATA:"SET_ASSETS_DATA",
    SET_TRACE_GRAPHICS_LAYER:"SET_TRACE_GRAPHICS_LAYER",
    SET_testTRACE_GRAPHICS_LAYER:"SET_testTRACE_GRAPHICS_LAYER",
    CLEAR_TRACE_GRAPHICS_LAYER:"CLEAR_TRACE_GRAPHICS_LAYER",
    SET_TRACE_ERROR_MESSAGE:"SET_TRACE_ERROR_MESSAGE",
    CLEAR_TRACE_ERROR_MESSAGE:"CLEAR_TRACE_ERROR_MESSAGE",
    SET_SELECTED_TRACE_TYPE:"SET_SELECTED_TRACE_TYPE",
    CLEAR_TRACE_SELECTED_POINTS:"CLEAR_TRACE_SELECTED_POINTS",
    SET_TRACE_LAYERS_DATA:"SET_TRACE_LAYERS_DATA",

    // find actions

    // sidebar actions

    //connectionExplorer actions

    //validate actions

    //selection actions
    SET_SELECTED_FEATURES:"SET_SELECTED_FEATURES",
    SET_EXPANDED_GROUPS:"SET_EXPANDED_GROUPS",
    SET_EXPANDED_TYPES :"SET_EXPANDED_TYPES",
    SET_EXPANDED_OBJECTS:"SET_EXPANDED_OBJECTS"

    //networkDiagram actions

    //containmentExplorer actions


    
    
};