export const ActionTypes = {
  // layout actions
  SET_LOADER: "SET_LOADER",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  SET_USER_DATA: "SET_USER_DATA",

  // mapView actions
  SET_VIEW: "SET_VIEW",
  SET_WEBMAP: "SET_WEBMAP",
  SET_LAYERS_AND_TABLES_DATA: "SET_LAYERS_AND_TABLES_DATA",
  SET_NETWORK_SERVICE: "SET_NETWORK_SERVICE",
  SET_UTILITYNETWORK: "SET_UTILITYNETWORK",

  // bookMark actions
  FILL_BOOKMARKS: "FILL_BOOKMARKS",
  BOOKMARK_FILTER_TEXT: "BOOKMARK_FILTER_TEXT",

  // mapContainer actions

  // ui actions
  SET_BOOKMARK_VISIBLITY: "SET_BOOKMARK_VISIBLITY",
  SET_ZINDEX_PANEL: "SET_ZINDEX_PANEL",

  // layerList actions

  // trace actions
  SET_TRACE_CONFIGURATIONS: "SET_TRACE_CONFIGURATIONS",
  ADD_TRACE_SELECTED_POINT: "ADD_TRACE_SELECTED_POINT",
  REMOVE_TRACE_POINT: "REMOVE_TRACE_POINT",
  SET_TRACE_RESULTS_ELEMENTS: "SET_TRACE_RESULTS_ELEMENTS",
  SET_TRACE_CONFIG_HIGHLIGHTS: "SET_TRACE_CONFIG_HIGHLIGHTS",
  SET_TRACE_GRAPHICS_LAYER: "SET_TRACE_GRAPHICS_LAYER",
  SET_TRACE_ERROR_MESSAGE: "SET_TRACE_ERROR_MESSAGE",
  SET_SELECTED_TRACE_TYPE: "SET_SELECTED_TRACE_TYPE",
  CLEAR_TRACE_SELECTED_POINTS: "CLEAR_TRACE_SELECTED_POINTS",
  SET_TRACE_RESULT_GLOBAL_IDS: "SET_TRACE_RESULT_GLOBAL_IDS",
  SET_QUERIED_TRACE_RESULT_FEATURES_MAP:
    "SET_QUERIED_TRACE_RESULT_FEATURES_MAP",

  // find actions
  SET_DISPLAY_SEARCH_RESULTS: "SET_DISPLAY_SEARCH_RESULTS",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",

  // sidebar actions
  SET_ACTIVE_BUTTON: "SET_ACTIVE_BUTTON",
  SET_SHOW_SIDEBAR: "SET_SHOW_SIDEBAR",

  //connectionExplorer actions

  //validate actions

  //selection actions
  SET_IS_GETTING_SELECTION_DATA: "SET_IS_GETTING_SELECTION_DATA",
  SET_SELECTED_FEATURES: "SET_SELECTED_FEATURES",
  SET_EXPANDED_GROUPS: "SET_EXPANDED_GROUPS",
  SET_EXPANDED_TYPES: "SET_EXPANDED_TYPES",
  SET_EXPANDED_OBJECTS: "SET_EXPANDED_OBJECTS",

  //networkDiagram actions
  SET_NETWORK_DIAGRAM_SPLITTER_VISIBLE: "SET_NETWORK_DIAGRAM_SPLITTER_VISIBLE",
  SET_NETWORK_DIAGRAM_VIEW:"SET_NETWORK_DIAGRAM_VIEW",
  SET_EXPORT_DIAGRAM_URL:"SET_EXPORT_DIAGRAM_URL",

  //containmentExplorer actions

  //map setting
  SET_MAP_SETTING_VISIBLITY: "SET_MAP_SETTING_VISIBLITY",
  SET_MAP_SETTING_ACTIVE_BUTTON: "SET_MAP_SETTING_ACTIVE_BUTTON",
  SET_NETWORK_SERVICES_VISIBLITY: "SET_NETWORK_SERVICES_VISIBLITY",
  SET_LAYER_ALIASES_VISIBLITY: "SET_LAYER_ALIASES_VISIBLITY",
  SET_SEARCHABLE_LAYERS_VISIBLITY: "SET_SEARCHABLE_LAYERS_VISIBLITY",
  SET_PROPERTIES_LAYER_FIELDS_VISIBLITY:
    "SET_PROPERTIES_LAYER_FIELDS_VISIBLITY",
  SET_RESULT_DETAILS_LAYER_FIELDS_VISIBLITY:
    "SET_RESULT_DETAILS_LAYER_FIELDS_VISIBLITY",
  SET_IDENTIFY_DETAILS_LAYER_FIELDS_VISIBLITY:
    "SET_IDENTIFY_DETAILS_LAYER_FIELDS_VISIBLITY",
  SET_NETWORK_SERVICE_CONFIG: "SET_NETWORK_SERVICE_CONFIG",
  SET_UTILITY_NETWORK_MAP_SETTING: "SET_UTILITY_NETWORK_MAP_SETTING",
  SET_FEATURE_SERVICE_LAYERS: "SET_FEATURE_SERVICE_LAYERS",
  SET_NETWORK_LAYERS_CACHE: "SET_NETWORK_LAYERS_CACHE",

  //show properties actions
  SET_SHOW_PROPERTIES_FEATURE: "SET_SHOW_PROPERTIES_FEATURE",

  //connection
  SET_CONNECTION_VISIBLITY: "SET_CONNECTION_VISIBLITY",
  SET_CONNECTION_FullSCREEN: "SET_CONNECTION_FullSCREEN",
  SET_CONNECTION_PARENT_FEATURE: "SET_CONNECTION_PARENT_FEATURE",

  //attachment
  SET_ATTACHMENT_VISIBLITY: "SET_ATTACHMENT_VISIBLITY",
  SET_ATTACHMENT_PARENT_FEATURE: "SET_ATTACHMENT_PARENT_FEATURE",

  //Containment
  SET_CONTAINMENT_VISIBLITY: "SET_CONTAINMENT_VISIBLITY",
  SET_CONTAINMENT_PARENT_FEATURE: "SET_CONTAINMENT_PARENT_FEATURE",
};
